[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[lib]

[features]
default = []
profiler= ["cpuprofiler"]

[dependencies]
argh= "0.1.3"
regex="1.4.2"
cpuprofiler = {version= "0.0.4", optional=true}
restructure = "0.2.0"
nom = "6.0.1"
