[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
smallvec = {version = "1.8.0", features = ["union", "const_generics"]}

[dev-dependencies]
criterion = "0.3"
cpuprofiler = "0.0.4"

[[bench]]
name = "benches"
harness = false

[profile.bench]
debug = true
